version: "3"

services:
  foundry:
    container_name: foundryvtt
    image: felddy/foundryvtt:release
    ports:
      - ${APP_PORT}:30000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - TZ=${TZ}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    dns:
      - "8.8.8.8"
    network_mode: "bridge"
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.foundryvtt-web-redirect.redirectscheme.scheme: https
      traefik.http.services.foundryvtt.loadbalancer.server.port: 30000
      # Web
      traefik.http.routers.foundryvtt-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.foundryvtt-insecure.entrypoints: web
      traefik.http.routers.foundryvtt-insecure.service: foundryvtt
      traefik.http.routers.foundryvtt-insecure.middlewares: foundryvtt-web-redirect
      # Websecure
      traefik.http.routers.foundryvtt.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.foundryvtt.entrypoints: websecure
      traefik.http.routers.foundryvtt.service: foundryvtt
      traefik.http.routers.foundryvtt.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.foundryvtt-local-insecure.rule: Host(`foundryvtt.${LOCAL_DOMAIN}`)
      traefik.http.routers.foundryvtt-local-insecure.entrypoints: web
      traefik.http.routers.foundryvtt-local-insecure.service: foundryvtt
      traefik.http.routers.foundryvtt-local-insecure.middlewares: foundryvtt-web-redirect
      # Local domain secure
      traefik.http.routers.foundryvtt-local.rule: Host(`foundryvtt.${LOCAL_DOMAIN}`)
      traefik.http.routers.foundryvtt-local.entrypoints: websecure
      traefik.http.routers.foundryvtt-local.service: foundryvtt
      traefik.http.routers.foundryvtt-local.tls: true
